version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "10000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - AVIATIONSTACK_API_KEY=${AVIATIONSTACK_API_KEY}
    volumes:
      - data_volume:/app/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_URL=http://backend:8000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - backend

volumes:
  data_volume:
